name: Check Difference
on: [push]
jobs:
  run_programs:
    name: run_first_program
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: python find_lowest_number.py test1_input.txt test1_output.txt
    name: run_second_program
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: python find_lowest_number.py test2_input.txt test2_output.txt
    name: run_third_program
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: python find_lowest_number.py test3_input.txt test3_output.txt
  check_diffs:
    name: check_first_diff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: diff test1_output.txt test1_expected.txt
    name: check_second_diff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: diff test2_output.txt test2_expected.txt
    name: check_third_diff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: diff test3_output.txt test3_expected.txt
