name: Check Difference
on: [push]
jobs:
  run_programs:
    name: Run first program
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: python find_lowest_number.py test1_input.txt test1_output.txt
    name: Run second program
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: python find_lowest_number.py test2_input.txt test2_output.txt
    name: Run third program
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: python find_lowest_number.py test3_input.txt test3_output.txt
  check_diffs:
    name: Check first difference
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: diff test1_output.txt test1_expected.txt
    name: Check second difference
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: diff test2_output.txt test2_expected.txt
    name: Check third difference
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: diff test3_output.txt test3_expected.txt
