name: Check Difference
on: [push]
jobs:
  check_first_diff:
    name: Check first difference
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: diff test_data/test1_output.txt test_data/test1_expected.txt
  check_second_diff:
    name: Check second difference
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: diff test_data/test2_output.txt test_data/test2_expected.txt
  check_third_diff:
    name: Check third difference
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: diff test_data/test3_output.txt test_data/test3_expected.txt
