name: Testing Data
on: [push]
jobs: 
  run_programs:
    name: Run first program
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Produce test output 1
      run: python find_lowest_number.py > test_data/test1_output.txt
    - name: check first output
      run: python3 find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
    - name: Produce test output 2
      run: python find_lowest_number.py > test_data/test2_output.txt
    - name: check second output
      run: python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
    - name: Produce test output 3
      run: python find_lowest_number.py > test_data/test3_output.txt
    - name: check third output
      run: python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
  
