name: Testing Data
on: [push]
jobs: 
  run__first_program:
    name: Run first program
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: python3 find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
  run__second_program:
    name: Run second program
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
  run__third_program:
    name: Run third program
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check outputs
      run: python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
  
